# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4254759d3d33458bc17c8d552eb6cbbe45921e62b7bd6442abfde34fc97a0c1d63a7291af59ca3af2236fc67d943d6ad092ae9ee1fbfc2169cb6348acbb19c2a

test:
  secret_key_base: bb8aa0acfc577c5b0c1d4904ac0957de9c0dc8995705d7b17fdde8c26efba0de0b79b7d92b58d8c9fd19d9cd4ea64aa0d328c532773c8609237060b092a0e994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
